DROP TABLE IF EXISTS PRESENTE;
DROP TABLE IF EXISTS REPRESENTATION;
DROP TABLE IF EXISTS LIEU;
DROP TABLE IF EXISTS UTILISATION;
DROP TABLE IF EXISTS ACCESSOIRE;
DROP TABLE IF EXISTS INTERPRETE;
DROP TABLE IF EXISTS NUMERO;
DROP TABLE IF EXISTS ARTISTE;
